# Generated by Django 6.0.3 on 2026-04-07 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.IntegerField()),
                ('salutation', models.CharField(blank=True, max_length=20)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('sna_category_original', models.CharField(blank=True, max_length=100)),
                ('sna_category', models.CharField(blank=True, max_length=50)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('organization_original', models.CharField(blank=True, max_length=200)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('active_inactive', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('conference', models.CharField(blank=True, max_length=20)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'attendances',
                'indexes': [models.Index(fields=['year'], name='core_attend_year_3a2acf_idx'), models.Index(fields=['sna_category'], name='core_attend_sna_cat_4de7c4_idx'), models.Index(fields=['organization'], name='core_attend_organiz_2e6a06_idx')],
            },
        ),
    ]
