# Generated by Django 4.2.17 on 2026-04-11 20:53

import apps.analysis.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('uploaded_file', models.FileField(upload_to=apps.analysis.models.upload_path)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('error', 'Error')], default='pending', max_length=15)),
                ('error_message', models.TextField(blank=True)),
                ('row_count', models.IntegerField(blank=True, null=True)),
                ('unique_orgs', models.IntegerField(blank=True, null=True)),
                ('unique_events', models.IntegerField(blank=True, null=True)),
                ('year_min', models.IntegerField(blank=True, null=True)),
                ('year_max', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.IntegerField(blank=True, null=True)),
                ('salutation', models.CharField(blank=True, max_length=20)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('sna_category_original', models.CharField(blank=True, max_length=100)),
                ('sna_category', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('title_cleaned', models.CharField(blank=True, max_length=255)),
                ('organization_original', models.CharField(blank=True, max_length=255)),
                ('organization', models.CharField(blank=True, max_length=255)),
                ('active_inactive', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=5)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('conference', models.CharField(blank=True, max_length=10)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='analysis.dataset')),
            ],
            options={
                'indexes': [models.Index(fields=['dataset', 'year'], name='analysis_at_dataset_987863_idx'), models.Index(fields=['dataset', 'sna_category'], name='analysis_at_dataset_cbb2ac_idx'), models.Index(fields=['dataset', 'organization'], name='analysis_at_dataset_88fb4d_idx')],
            },
        ),
    ]
